

CREATE TABLE CLIENTE (
    IDCLIENTE INT GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_CELULAR VARCHAR(20) NOT NULL UNIQUE,
	CONSTRAINT CHK_CPF_FORMAT CHECK (CPF ~ '^[0-9]{11}$'), 
	PRIMARY KEY(IDCLIENTE)
);

CREATE TABLE FUNCIONARIO (
    IDFUNCIONARIO INT GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_CELULAR VARCHAR(20) NOT NULL UNIQUE,
    SALARIO NUMERIC(10,2) NOT NULL,
    ESPECIALIDADE VARCHAR(30) NOT NULL,
    COMISSAO NUMERIC(5,2) NOT NULL,
	CONSTRAINT CHK_CPF_FORMAT CHECK (CPF ~ '^[0-9]{11}$'), 
	PRIMARY KEY(IDFUNCIONARIO)
);

CREATE TABLE CATEGORIA (
    IDCATEGORIA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SERVICO (
    IDSERVICO INT GENERATED ALWAYS AS IDENTITY,
    NOME_SERVICO VARCHAR(100) NOT NULL UNIQUE,
    VALOR NUMERIC(10,2) NOT NULL,
    ID_CATEGORIA INT NOT NULL, 
    DURACAO INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA),
	PRIMARY KEY(IDSERVICO)
);

CREATE TABLE AGENDA (
    IDAGENDA INT GENERATED ALWAYS AS IDENTITY,
    IDCLIENTE INT NOT NULL,
    IDFUNCIONARIO INT NOT NULL,
    IDSERVICO INT NOT NULL,
    DIA DATE NOT NULL,
    HORARIO TIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
    FOREIGN KEY (IDSERVICO) REFERENCES SERVICO(IDSERVICO),
	PRIMARY KEY(IDAGENDA)
);

CREATE TABLE PAGAMENTO (
    IDPAGAMENTO INT GENERATED ALWAYS AS IDENTITY,
    IDAGENDA INT NOT NULL,
    VALOR NUMERIC(10,2) NOT NULL,
    FORMA_PAGAMENTO VARCHAR(30) NOT NULL,
    DATA_PAGAMENTO TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (IDAGENDA) REFERENCES AGENDA(IDAGENDA),
	PRIMARY KEY(IDPAGAMENTO)
);

CREATE TABLE disponibilidade (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    funcionario_id INT NOT NULL,
    dia_semana VARCHAR(10) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fim TIME NOT NULL,
    FOREIGN KEY (funcionario_id) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
    CONSTRAINT disponibilidade_unica UNIQUE(funcionario_id, dia_semana, hora_inicio, hora_fim)
);


