CREATE TABLE CLIENTE (
    IDCLIENTE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CPF CHAR(11) NOT NULL UNIQUE,
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_CELULAR VARCHAR(20) NOT NULL UNIQUE,
    CONSTRAINT CHK_CPF_CLIENTE_FORMAT CHECK (CPF ~ '^[0-9]{11}$')
);

CREATE TABLE FUNCIONARIO (
    IDFUNCIONARIO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CPF CHAR(11) NOT NULL UNIQUE,
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_CELULAR VARCHAR(20) NOT NULL UNIQUE,
    SALARIO NUMERIC(10,2) NOT NULL,
    ESPECIALIDADE VARCHAR(30) NOT NULL,
    CONSTRAINT CHK_CPF_FUNCIONARIO_FORMAT CHECK (CPF ~ '^[0-9]{11}$')
);

CREATE TABLE CATEGORIA (
    IDCATEGORIA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_CATEGORIA VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE SERVICO (
    IDSERVICO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE,
    VALOR NUMERIC(10,2) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    DURACAO INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(IDCATEGORIA)
);

CREATE TABLE AGENDA (
    IDAGENDA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    ID_SERVICO INT NOT NULL,
    DIA DATE NOT NULL,
    HORARIO TIME NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(IDSERVICO)
);

CREATE TABLE COMPRA (
    IDCOMPRA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATA_COMPRA TIMESTAMP NOT NULL DEFAULT NOW(),
    VALOR_TOTAL NUMERIC(10,2) NOT NULL
);

CREATE TABLE PAGAMENTO (
    IDPAGAMENTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_AGENDA INT NULL,
    ID_COMPRA INT NULL,
    VALOR NUMERIC(10,2) NOT NULL CHECK (VALOR > 0),
    FORMA_PAGAMENTO VARCHAR(30) NOT NULL CHECK (
        FORMA_PAGAMENTO IN ('DINHEIRO','CARTAO_DEBITO','CARTAO_CREDITO','PIX','TRANSFERENCIA')),
    DATA_PAGAMENTO TIMESTAMP NOT NULL DEFAULT NOW(),
    STATUS VARCHAR(20) DEFAULT 'APROVADO' CHECK (
        STATUS IN ('PENDENTE','APROVADO','RECUSADO','ESTORNADO')),
    FOREIGN KEY (ID_AGENDA) REFERENCES AGENDA(IDAGENDA),
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(IDCOMPRA),
    CONSTRAINT CHK_PAGAMENTO_ORIGEM CHECK (
        (ID_AGENDA IS NOT NULL AND ID_COMPRA IS NULL) OR
        (ID_AGENDA IS NULL AND ID_COMPRA IS NOT NULL))
);

CREATE TABLE DISPONIBILIDADE (
    IDDISPONIBILIDADE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    DIA_SEMANA VARCHAR(10) NOT NULL,
    HORA_INICIO TIME NOT NULL,
    HORA_FIM TIME NOT NULL,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO),
    CONSTRAINT DISPONIBILIDADE_UNICA UNIQUE(ID_FUNCIONARIO, DIA_SEMANA, HORA_INICIO, HORA_FIM)
);

CREATE TABLE PRODUTO (
    IDPRODUTO INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL UNIQUE,
    VALOR NUMERIC(10,2) NOT NULL,
    TIPO VARCHAR(50) NOT NULL
);

CREATE TABLE ESTOQUE (
    IDESTOQUE INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRODUTO INT NOT NULL UNIQUE,
    QUANTIDADE_ATUAL INT NOT NULL DEFAULT 0,
    QUANTIDADE_MINIMA INT NOT NULL DEFAULT 0,
    ULTIMA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE UTILIZA (
    IDUTILIZA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SERVICO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(IDSERVICO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE ITENS_COMPRA (
    IDITENSCOMPRA INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMPRA INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    VALOR_UNITARIO NUMERIC(10,2) NOT NULL,
    VALOR_TOTAL_ITEM NUMERIC(10,2) NOT NULL,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA(IDCOMPRA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);
